Handlebars template
galynskyy/FirstProject pull request #56
Opened 2017-03-03 06:02 UTC by sychuginaanna

Сделала хелпер. Не поняла, как можно заново высчитывать по формуле. у нас же "отрисовка" идет в зависимости от того, сколько выбрано пунктов. при загрузке страницы сделала, что выбраны 3 пункта
Данные о пользователе подставляю с помощью handlebars, а также названия начальных задач.

2017-03-03 17:45 UTC, Afelua commented on src/partials/user.hbs
> +				{{sureName}} {{name}}
Фамилия и Имя лучше сделать элементами одного объекта http://handlebarsjs.com/expressions.html

2017-03-03 17:49 UTC, Afelua commented on src/partials/goal.hbs
>  				<label for="checkbox4" class="goal-task__label">Лендинг для корпоратива</label>
Почему состояние checkbox вынесено в шаблон только для первых трех элементов, а для остальных трех - нет?

2017-03-03 17:51 UTC, Afelua commented on src/partials/calendar.hbs
> +		{{#each tasks}}
Т.е. состояние data-progress("_done", "_delay", "_proc") уже не актуально, правильно понимаю? Если да, то почему?

2017-03-03 17:53 UTC, Afelua commented on src/index.hbs
> +		<script src="scripts/min.js"></script>
min.js - обычно так называет оптимизированный js-файл (оригинал - script.js, а оптимизированный - script.min.js ). Вы преследовали ту же идею?)

2017-03-03 17:54 UTC, Afelua commented on src/data.json
> +   "checkbox1" : "1",
В checkbox стоит задать значение boolean (true или false)

2017-03-03 17:55 UTC, Afelua commented on gulpfile.js
> +                return currentValue == '1' ? ' checked="checked"' : '';
После исправления комментария ниже с boolean внедрить новую логику проверки

2017-03-11 13:15 UTC, sychuginaanna commented on src/partials/calendar.hbs
> +		{{#each tasks}}
Я их убрала пока. Они будут добавляться динамически через js. Данный скрипт я пишу на ветке js-calendar-new

2017-03-11 13:15 UTC, sychuginaanna commented on src/index.hbs
> +		<script src="scripts/min.js"></script>
исправила на script.min.js

2017-03-11 13:19 UTC, sychuginaanna commented on gulpfile.js
> +                return currentValue == '1' ? ' checked="checked"' : '';
+

2017-03-11 14:36 UTC, Afelua requested changes

2017-03-11 14:36 UTC, Afelua commented on gulpfile.js
> +                return currentValue == 'true' ? ' checked="checked"' : '';
`currentValue == 'true` можно заменить просто `currentValue`

2017-03-11 14:36 UTC, Afelua commented on src/data.json
> -   "sureName": "Doe",
surname

2017-03-11 14:36 UTC, Afelua commented on src/data.json
> +   "checkbox1" : "true",
просто true и false, без кавычек

2017-03-22 07:58 UTC, Afelua commented on src/partials/goal.hbs
> +			<label for="{{id}}" class="goal-task__label">{{tittle}}</label>
Title с одной t - просьба исправить в след коммите

2017-03-22 08:01 UTC, Afelua approved these changes

2017-03-22 14:51 UTC, merged